import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useMemo, useState } from 'react';
import { previewPlanning, savePlanning, planningHistory, type PlanningSummary } from '@/lib/planning.functions';
import { formatAUD } from '@/lib/score';
export const Route=createFileRoute('/_authenticated/app/planning')({component:PlanningPage});
function PlanningPage(){
  const [summary,setSummary]=useState<PlanningSummary|null>(null),[history,setHistory]=useState<any[]>([]),[planId,setPlanId]=useState<string|undefined>(),[extra,setExtra]=useState(0),[targetMonths,setTargetMonths]=useState(6),[contributions,setContributions]=useState<Record<string,number>>({}),[customOrder,setCustomOrder]=useState<string[]>([]),[saving,setSaving]=useState(false),[error,setError]=useState('');
  async function load(){try{const [preview,plans]=await Promise.all([previewPlanning(),planningHistory()]) as [PlanningSummary,any[]];setSummary(preview);setHistory(plans);const current=plans[0];if(current){setPlanId(String(current.id));setExtra(Number(current.config?.extraDebtPayment||0));setTargetMonths(Number(current.config?.emergencyTargetMonths||6));setContributions(current.config?.goalContributions||{});setCustomOrder((current.config?.customDebtOrder||[]).map(String));}else{setCustomOrder((preview.debt_plans.find(p=>p.strategy==='custom')?.payoff_order||[]).map(d=>String(d.id)));}}catch(e){setError(e instanceof Error?e.message:'Could not load planning');}}
  useEffect(()=>{load();},[]);
  const plans=useMemo(()=>summary?.debt_plans||[],[summary]);
  async function save(){setSaving(true);setError('');try{const result:any=await savePlanning({planId,name:'My financial plan',extraDebtPayment:extra,emergencyTargetMonths:targetMonths,goalContributions:contributions,customDebtOrder:customOrder});setPlanId(String(result.id));setSummary(result.latest_summary);setHistory(await planningHistory());}catch(e){setError(e instanceof Error?e.message:'Could not save');}finally{setSaving(false);}}
  function moveDebt(index:number,direction:number){const next=[...customOrder],target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setCustomOrder(next);}
  return <div className="max-w-6xl mx-auto px-6 md:px-10 py-10">
    <h1 className="text-[32px] tracking-display font-bold">Financial plan</h1><p className="text-[13px] text-muted-foreground mt-1 mb-7">Turn live goals, cash and debts into a measurable monthly plan.</p>
    {error&&<p className="mb-4 rounded-lg border border-destructive/40 p-3 text-sm text-destructive">{error}</p>}
    {!summary?<div className="text-sm text-muted-foreground">Calculating your plan…</div>:<>
      <section className="grid md:grid-cols-3 gap-4 mb-8">
        <Metric label="Goals on track" value={`${summary.outcomes.goals_on_track} / ${summary.outcomes.goals_total}`} detail="Based on required monthly contributions"/>
        <Metric label="Emergency cover" value={summary.emergency_fund.coverage_months==null?'Add expenses':`${summary.emergency_fund.coverage_months} months`} detail={`${formatAUD(summary.emergency_fund.gap)} remaining to target`}/>
        <Metric label="Projected debt-free" value={summary.outcomes.projected_debt_free_date||'Add debt payments'} detail={summary.outcomes.recommended_debt_strategy?`${summary.outcomes.recommended_debt_strategy} has the lowest interest`:'No feasible plan yet'}/>
      </section>
      <section className="rounded-[14px] border border-border bg-[var(--surface)] p-5 mb-6"><h2 className="font-semibold mb-4">Monthly settings</h2><div className="grid sm:grid-cols-2 gap-4"><label className="text-xs text-muted-foreground">Emergency target (months)<input className="block mt-1 w-full rounded-lg border border-border bg-background p-2 text-foreground" type="number" min="1" max="24" value={targetMonths} onChange={e=>setTargetMonths(Number(e.target.value))}/></label><label className="text-xs text-muted-foreground">Extra debt payment<input className="block mt-1 w-full rounded-lg border border-border bg-background p-2 text-foreground" type="number" min="0" value={extra} onChange={e=>setExtra(Number(e.target.value))}/></label></div><button onClick={save} disabled={saving} className="mt-4 rounded-lg bg-mint px-4 py-2 text-sm font-semibold text-black disabled:opacity-50">{saving?'Saving…':'Save plan & capture progress'}</button></section>
      <section className="grid lg:grid-cols-2 gap-6"><div><h2 className="font-semibold mb-3">Goal feasibility</h2><div className="space-y-3">{summary.goals.length?summary.goals.map(g=><div key={g.goal_id} className="rounded-xl border border-border p-4"><div className="flex justify-between"><b className="text-sm">{g.name}</b><Status value={g.status}/></div><p className="text-xs text-muted-foreground mt-2">{g.status==='needs_target_date'?'Add a target date to calculate the required contribution':g.required_monthly_contribution==null?'Target date has passed':`${formatAUD(g.required_monthly_contribution)} required each month`}{g.monthly_shortfall?` · ${formatAUD(g.monthly_shortfall)} shortfall`:''}</p><label className="mt-3 block text-[11px] text-muted-foreground">Planned monthly contribution<input className="mt-1 w-full rounded-lg border border-border bg-background p-2 text-foreground" type="number" min="0" value={contributions[g.goal_id]??0} onChange={e=>setContributions({...contributions,[g.goal_id]:Number(e.target.value)})}/></label></div>):<Empty text="Add a goal and target date to calculate feasibility."/>}</div></div>
      <div><h2 className="font-semibold mb-3">Debt strategies</h2><div className="space-y-3">{plans.some(p=>p.starting_balance>0)?plans.map(p=><div key={p.strategy} className="rounded-xl border border-border p-4"><div className="flex justify-between"><b className="text-sm capitalize">{p.strategy}</b><span className="text-xs">{p.months_to_debt_free??'—'} months</span></div><p className="text-xs text-muted-foreground mt-2">{formatAUD(p.total_interest)} projected interest · {p.debt_free_date||'payment is below accrued interest'}</p></div>):<Empty text="Add balances, rates and minimum payments under Liabilities."/>}</div></div></section>
      <section className="mt-8"><h2 className="font-semibold mb-3">Custom payoff order</h2><div className="rounded-xl border border-border divide-y divide-border">{customOrder.map((id,index)=>{const debt=plans.find(p=>p.strategy==='custom')?.payoff_order.find(d=>String(d.id)===id);return <div key={id} className="flex items-center justify-between p-3 text-sm"><span>{index+1}. {debt?.label||`Debt ${id}`}</span><span><button className="px-2" onClick={()=>moveDebt(index,-1)} aria-label="Move up">↑</button><button className="px-2" onClick={()=>moveDebt(index,1)} aria-label="Move down">↓</button></span></div>})}</div></section>
      <section className="mt-8"><h2 className="font-semibold mb-3">Progress and outcomes</h2>{history.length?<div className="rounded-xl border border-border overflow-hidden">{history.map(p=>{const snaps=p.snapshots||[],first=snaps[0]?.summary?.outcomes,last=snaps.at(-1)?.summary?.outcomes,debtChange=first&&last?Number(first.debt_reduction_target)-Number(last.debt_reduction_target):0;return <div key={p.id} className="flex justify-between gap-4 border-b border-border last:border-0 p-4 text-sm"><span>{p.name}<small className="block text-muted-foreground">{snaps.length>1?`${formatAUD(debtChange)} measured debt reduction · goals on track ${last?.goals_on_track}/${last?.goals_total}`:'Save another check-in to measure change'}</small></span><span className="text-muted-foreground whitespace-nowrap">{snaps.length} check-ins · {new Date(p.updated_at).toLocaleDateString('en-AU')}</span></div>})}</div>:<Empty text="Save this plan to begin tracking outcomes over time."/>}</section>
    </>}
    <p className="mt-12 text-center text-[11px] text-muted-foreground">Maal does not provide financial advice. Any information provided by Maal is for educational purposes only.</p>
  </div>;
}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <div className="rounded-[14px] border border-border bg-[var(--surface)] p-5"><p className="text-xs text-muted-foreground">{label}</p><p className="text-xl font-bold mt-2">{value}</p><p className="text-[11px] text-muted-foreground mt-2">{detail}</p></div>}
function Status({value}:{value:string}){return <span className="rounded-full bg-mint/15 px-2 py-1 text-[10px] uppercase text-mint">{value.replace('_',' ')}</span>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-border p-5 text-xs text-muted-foreground">{text}</div>}
