import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { createZakatRun, listServiceRuns } from "@/lib/wealth-services.functions";

export const Route = createFileRoute("/_authenticated/app/zakat")({ component: ZakatPage });
type Run={id:string;status:string;created_at:string;result:{zakatDueMinor?:string;zakatableBaseMinor?:string}};
function money(v?:string){return new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(Number(v||0)/100)}
function ZakatPage(){
  const today=new Date().toISOString().slice(0,10); const [valuationDate,setDate]=useState(today);const [nisab,setNisab]=useState("12000");const [cash,setCash]=useState("0");const [debt,setDebt]=useState("0");const [result,setResult]=useState<any>();const [runs,setRuns]=useState<Run[]>([]);const [error,setError]=useState("");
  const refresh=()=>listServiceRuns("zakat").then(j=>setRuns(j.runs||[]));useEffect(()=>{void refresh()},[]);
  async function calculate(){setError("");const lines=[{key:"confirmed-cash",category:"cash",amountMinor:String(Math.round(Number(cash)*100)),confirmed:true,evidence:{source:"user_confirmed"}},{key:"short-term-debt",category:"deductible_debt",amountMinor:String(Math.round(Number(debt)*100)),dueWithinMonths:12,confirmed:true,evidence:{source:"user_confirmed"}}];try{const j=await createZakatRun({valuationDate,nisabMinor:String(Math.round(Number(nisab)*100)),methodology:"LUNAR_V1",lines});setResult(j);refresh();}catch(e){setError(e instanceof Error?e.message:"Calculation failed")}}
  return <div className="mx-auto max-w-4xl p-6 space-y-6"><div><h1 className="text-2xl font-bold">Zakat</h1><p className="text-sm text-muted-foreground">A versioned 2.5% lunar-year estimate with a saved evidence snapshot. Confirm every classification before relying on it.</p></div><div className="grid gap-4 rounded-xl border border-border bg-[var(--surface)] p-5 md:grid-cols-2"><label className="text-sm">Valuation date<input className="mt-1 w-full rounded border border-border bg-background p-2" type="date" value={valuationDate} onChange={e=>setDate(e.target.value)}/></label><label className="text-sm">Nisab basis (AUD)<input className="mt-1 w-full rounded border border-border bg-background p-2" type="number" value={nisab} onChange={e=>setNisab(e.target.value)}/></label><label className="text-sm">Eligible cash/assets (AUD)<input className="mt-1 w-full rounded border border-border bg-background p-2" type="number" value={cash} onChange={e=>setCash(e.target.value)}/></label><label className="text-sm">Debts due within 12 months (AUD)<input className="mt-1 w-full rounded border border-border bg-background p-2" type="number" value={debt} onChange={e=>setDebt(e.target.value)}/></label><button onClick={calculate} className="rounded bg-mint px-4 py-2 font-semibold text-black">Calculate and save snapshot</button>{error&&<p className="text-sm text-red-500">{error}</p>}</div>{result&&<div className="rounded-xl border border-mint/40 p-5"><p className="text-sm text-muted-foreground">Estimated zakat due</p><p className="text-3xl font-bold">{money(result.zakatDueMinor)}</p><p className="mt-2 text-xs text-amber-600">Methodology activation: qualified scholarly review required. Educational calculation only.</p><a className="mt-3 inline-block text-sm text-mint underline" href={`/api/v1/service-runs/${result.runId}/evidence`}>Download evidence</a></div>}<section><h2 className="font-semibold">History</h2><div className="mt-2 space-y-2">{runs.map(run=><div key={run.id} className="flex justify-between rounded border border-border p-3 text-sm"><span>{new Date(run.created_at).toLocaleDateString("en-AU")} · {run.status}</span><b>{money(run.result.zakatDueMinor)}</b></div>)}</div></section></div>;
}
