/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppVaultRouteImport } from './routes/_authenticated/app.vault'
import { Route as AuthenticatedAppTransactionsRouteImport } from './routes/_authenticated/app.transactions'
import { Route as AuthenticatedAppToolsRouteImport } from './routes/_authenticated/app.tools'
import { Route as AuthenticatedAppTaxOptimizerRouteImport } from './routes/_authenticated/app.tax-optimizer'
import { Route as AuthenticatedAppTaxBracketVisualizerRouteImport } from './routes/_authenticated/app.tax-bracket-visualizer'
import { Route as AuthenticatedAppSuperOptimizerRouteImport } from './routes/_authenticated/app.super-optimizer'
import { Route as AuthenticatedAppScenariosSimulatorRouteImport } from './routes/_authenticated/app.scenarios-simulator'
import { Route as AuthenticatedAppRoadmapRouteImport } from './routes/_authenticated/app.roadmap'
import { Route as AuthenticatedAppRetirementRouteImport } from './routes/_authenticated/app.retirement'
import { Route as AuthenticatedAppResearchRouteImport } from './routes/_authenticated/app.research'
import { Route as AuthenticatedAppReportRouteImport } from './routes/_authenticated/app.report'
import { Route as AuthenticatedAppRadarRouteImport } from './routes/_authenticated/app.radar'
import { Route as AuthenticatedAppPortfolioPlanRouteImport } from './routes/_authenticated/app.portfolio-plan'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated/app.onboarding'
import { Route as AuthenticatedAppNetWorthFlowRouteImport } from './routes/_authenticated/app.net-worth-flow'
import { Route as AuthenticatedAppInsuranceGapRouteImport } from './routes/_authenticated/app.insurance-gap'
import { Route as AuthenticatedAppGoalsRouteImport } from './routes/_authenticated/app.goals'
import { Route as AuthenticatedAppDebtPayoffRouteImport } from './routes/_authenticated/app.debt-payoff'
import { Route as AuthenticatedAppCostOfLivingRouteImport } from './routes/_authenticated/app.cost-of-living'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppAssetsRouteImport } from './routes/_authenticated/app.assets'
import { Route as AuthenticatedAppAdvisorIndexRouteImport } from './routes/_authenticated/app.advisor.index'
import { Route as AuthenticatedAppAdvisorThreadIdRouteImport } from './routes/_authenticated/app.advisor.$threadId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppVaultRoute = AuthenticatedAppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTransactionsRoute =
  AuthenticatedAppTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppToolsRoute = AuthenticatedAppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTaxOptimizerRoute =
  AuthenticatedAppTaxOptimizerRouteImport.update({
    id: '/tax-optimizer',
    path: '/tax-optimizer',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTaxBracketVisualizerRoute =
  AuthenticatedAppTaxBracketVisualizerRouteImport.update({
    id: '/tax-bracket-visualizer',
    path: '/tax-bracket-visualizer',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSuperOptimizerRoute =
  AuthenticatedAppSuperOptimizerRouteImport.update({
    id: '/super-optimizer',
    path: '/super-optimizer',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppScenariosSimulatorRoute =
  AuthenticatedAppScenariosSimulatorRouteImport.update({
    id: '/scenarios-simulator',
    path: '/scenarios-simulator',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRoadmapRoute = AuthenticatedAppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRetirementRoute =
  AuthenticatedAppRetirementRouteImport.update({
    id: '/retirement',
    path: '/retirement',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppResearchRoute =
  AuthenticatedAppResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReportRoute = AuthenticatedAppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRadarRoute = AuthenticatedAppRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPortfolioPlanRoute =
  AuthenticatedAppPortfolioPlanRouteImport.update({
    id: '/portfolio-plan',
    path: '/portfolio-plan',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNetWorthFlowRoute =
  AuthenticatedAppNetWorthFlowRouteImport.update({
    id: '/net-worth-flow',
    path: '/net-worth-flow',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInsuranceGapRoute =
  AuthenticatedAppInsuranceGapRouteImport.update({
    id: '/insurance-gap',
    path: '/insurance-gap',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGoalsRoute = AuthenticatedAppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDebtPayoffRoute =
  AuthenticatedAppDebtPayoffRouteImport.update({
    id: '/debt-payoff',
    path: '/debt-payoff',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCostOfLivingRoute =
  AuthenticatedAppCostOfLivingRouteImport.update({
    id: '/cost-of-living',
    path: '/cost-of-living',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAssetsRoute = AuthenticatedAppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdvisorIndexRoute =
  AuthenticatedAppAdvisorIndexRouteImport.update({
    id: '/advisor/',
    path: '/advisor/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdvisorThreadIdRoute =
  AuthenticatedAppAdvisorThreadIdRouteImport.update({
    id: '/advisor/$threadId',
    path: '/advisor/$threadId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/assets': typeof AuthenticatedAppAssetsRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/cost-of-living': typeof AuthenticatedAppCostOfLivingRoute
  '/app/debt-payoff': typeof AuthenticatedAppDebtPayoffRoute
  '/app/goals': typeof AuthenticatedAppGoalsRoute
  '/app/insurance-gap': typeof AuthenticatedAppInsuranceGapRoute
  '/app/net-worth-flow': typeof AuthenticatedAppNetWorthFlowRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/portfolio-plan': typeof AuthenticatedAppPortfolioPlanRoute
  '/app/radar': typeof AuthenticatedAppRadarRoute
  '/app/report': typeof AuthenticatedAppReportRoute
  '/app/research': typeof AuthenticatedAppResearchRoute
  '/app/retirement': typeof AuthenticatedAppRetirementRoute
  '/app/roadmap': typeof AuthenticatedAppRoadmapRoute
  '/app/scenarios-simulator': typeof AuthenticatedAppScenariosSimulatorRoute
  '/app/super-optimizer': typeof AuthenticatedAppSuperOptimizerRoute
  '/app/tax-bracket-visualizer': typeof AuthenticatedAppTaxBracketVisualizerRoute
  '/app/tax-optimizer': typeof AuthenticatedAppTaxOptimizerRoute
  '/app/tools': typeof AuthenticatedAppToolsRoute
  '/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/app/vault': typeof AuthenticatedAppVaultRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/advisor/$threadId': typeof AuthenticatedAppAdvisorThreadIdRoute
  '/app/advisor/': typeof AuthenticatedAppAdvisorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/assets': typeof AuthenticatedAppAssetsRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/cost-of-living': typeof AuthenticatedAppCostOfLivingRoute
  '/app/debt-payoff': typeof AuthenticatedAppDebtPayoffRoute
  '/app/goals': typeof AuthenticatedAppGoalsRoute
  '/app/insurance-gap': typeof AuthenticatedAppInsuranceGapRoute
  '/app/net-worth-flow': typeof AuthenticatedAppNetWorthFlowRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/portfolio-plan': typeof AuthenticatedAppPortfolioPlanRoute
  '/app/radar': typeof AuthenticatedAppRadarRoute
  '/app/report': typeof AuthenticatedAppReportRoute
  '/app/research': typeof AuthenticatedAppResearchRoute
  '/app/retirement': typeof AuthenticatedAppRetirementRoute
  '/app/roadmap': typeof AuthenticatedAppRoadmapRoute
  '/app/scenarios-simulator': typeof AuthenticatedAppScenariosSimulatorRoute
  '/app/super-optimizer': typeof AuthenticatedAppSuperOptimizerRoute
  '/app/tax-bracket-visualizer': typeof AuthenticatedAppTaxBracketVisualizerRoute
  '/app/tax-optimizer': typeof AuthenticatedAppTaxOptimizerRoute
  '/app/tools': typeof AuthenticatedAppToolsRoute
  '/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/app/vault': typeof AuthenticatedAppVaultRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/advisor/$threadId': typeof AuthenticatedAppAdvisorThreadIdRoute
  '/app/advisor': typeof AuthenticatedAppAdvisorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/assets': typeof AuthenticatedAppAssetsRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/cost-of-living': typeof AuthenticatedAppCostOfLivingRoute
  '/_authenticated/app/debt-payoff': typeof AuthenticatedAppDebtPayoffRoute
  '/_authenticated/app/goals': typeof AuthenticatedAppGoalsRoute
  '/_authenticated/app/insurance-gap': typeof AuthenticatedAppInsuranceGapRoute
  '/_authenticated/app/net-worth-flow': typeof AuthenticatedAppNetWorthFlowRoute
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/portfolio-plan': typeof AuthenticatedAppPortfolioPlanRoute
  '/_authenticated/app/radar': typeof AuthenticatedAppRadarRoute
  '/_authenticated/app/report': typeof AuthenticatedAppReportRoute
  '/_authenticated/app/research': typeof AuthenticatedAppResearchRoute
  '/_authenticated/app/retirement': typeof AuthenticatedAppRetirementRoute
  '/_authenticated/app/roadmap': typeof AuthenticatedAppRoadmapRoute
  '/_authenticated/app/scenarios-simulator': typeof AuthenticatedAppScenariosSimulatorRoute
  '/_authenticated/app/super-optimizer': typeof AuthenticatedAppSuperOptimizerRoute
  '/_authenticated/app/tax-bracket-visualizer': typeof AuthenticatedAppTaxBracketVisualizerRoute
  '/_authenticated/app/tax-optimizer': typeof AuthenticatedAppTaxOptimizerRoute
  '/_authenticated/app/tools': typeof AuthenticatedAppToolsRoute
  '/_authenticated/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/_authenticated/app/vault': typeof AuthenticatedAppVaultRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/advisor/$threadId': typeof AuthenticatedAppAdvisorThreadIdRoute
  '/_authenticated/app/advisor/': typeof AuthenticatedAppAdvisorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/assets'
    | '/app/billing'
    | '/app/cost-of-living'
    | '/app/debt-payoff'
    | '/app/goals'
    | '/app/insurance-gap'
    | '/app/net-worth-flow'
    | '/app/onboarding'
    | '/app/portfolio-plan'
    | '/app/radar'
    | '/app/report'
    | '/app/research'
    | '/app/retirement'
    | '/app/roadmap'
    | '/app/scenarios-simulator'
    | '/app/super-optimizer'
    | '/app/tax-bracket-visualizer'
    | '/app/tax-optimizer'
    | '/app/tools'
    | '/app/transactions'
    | '/app/vault'
    | '/app/'
    | '/app/advisor/$threadId'
    | '/app/advisor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/assets'
    | '/app/billing'
    | '/app/cost-of-living'
    | '/app/debt-payoff'
    | '/app/goals'
    | '/app/insurance-gap'
    | '/app/net-worth-flow'
    | '/app/onboarding'
    | '/app/portfolio-plan'
    | '/app/radar'
    | '/app/report'
    | '/app/research'
    | '/app/retirement'
    | '/app/roadmap'
    | '/app/scenarios-simulator'
    | '/app/super-optimizer'
    | '/app/tax-bracket-visualizer'
    | '/app/tax-optimizer'
    | '/app/tools'
    | '/app/transactions'
    | '/app/vault'
    | '/app'
    | '/app/advisor/$threadId'
    | '/app/advisor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/assets'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/cost-of-living'
    | '/_authenticated/app/debt-payoff'
    | '/_authenticated/app/goals'
    | '/_authenticated/app/insurance-gap'
    | '/_authenticated/app/net-worth-flow'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/portfolio-plan'
    | '/_authenticated/app/radar'
    | '/_authenticated/app/report'
    | '/_authenticated/app/research'
    | '/_authenticated/app/retirement'
    | '/_authenticated/app/roadmap'
    | '/_authenticated/app/scenarios-simulator'
    | '/_authenticated/app/super-optimizer'
    | '/_authenticated/app/tax-bracket-visualizer'
    | '/_authenticated/app/tax-optimizer'
    | '/_authenticated/app/tools'
    | '/_authenticated/app/transactions'
    | '/_authenticated/app/vault'
    | '/_authenticated/app/'
    | '/_authenticated/app/advisor/$threadId'
    | '/_authenticated/app/advisor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/vault': {
      id: '/_authenticated/app/vault'
      path: '/vault'
      fullPath: '/app/vault'
      preLoaderRoute: typeof AuthenticatedAppVaultRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/transactions': {
      id: '/_authenticated/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AuthenticatedAppTransactionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tools': {
      id: '/_authenticated/app/tools'
      path: '/tools'
      fullPath: '/app/tools'
      preLoaderRoute: typeof AuthenticatedAppToolsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tax-optimizer': {
      id: '/_authenticated/app/tax-optimizer'
      path: '/tax-optimizer'
      fullPath: '/app/tax-optimizer'
      preLoaderRoute: typeof AuthenticatedAppTaxOptimizerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tax-bracket-visualizer': {
      id: '/_authenticated/app/tax-bracket-visualizer'
      path: '/tax-bracket-visualizer'
      fullPath: '/app/tax-bracket-visualizer'
      preLoaderRoute: typeof AuthenticatedAppTaxBracketVisualizerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/super-optimizer': {
      id: '/_authenticated/app/super-optimizer'
      path: '/super-optimizer'
      fullPath: '/app/super-optimizer'
      preLoaderRoute: typeof AuthenticatedAppSuperOptimizerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/scenarios-simulator': {
      id: '/_authenticated/app/scenarios-simulator'
      path: '/scenarios-simulator'
      fullPath: '/app/scenarios-simulator'
      preLoaderRoute: typeof AuthenticatedAppScenariosSimulatorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/roadmap': {
      id: '/_authenticated/app/roadmap'
      path: '/roadmap'
      fullPath: '/app/roadmap'
      preLoaderRoute: typeof AuthenticatedAppRoadmapRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/retirement': {
      id: '/_authenticated/app/retirement'
      path: '/retirement'
      fullPath: '/app/retirement'
      preLoaderRoute: typeof AuthenticatedAppRetirementRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/research': {
      id: '/_authenticated/app/research'
      path: '/research'
      fullPath: '/app/research'
      preLoaderRoute: typeof AuthenticatedAppResearchRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/report': {
      id: '/_authenticated/app/report'
      path: '/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AuthenticatedAppReportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/radar': {
      id: '/_authenticated/app/radar'
      path: '/radar'
      fullPath: '/app/radar'
      preLoaderRoute: typeof AuthenticatedAppRadarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/portfolio-plan': {
      id: '/_authenticated/app/portfolio-plan'
      path: '/portfolio-plan'
      fullPath: '/app/portfolio-plan'
      preLoaderRoute: typeof AuthenticatedAppPortfolioPlanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/net-worth-flow': {
      id: '/_authenticated/app/net-worth-flow'
      path: '/net-worth-flow'
      fullPath: '/app/net-worth-flow'
      preLoaderRoute: typeof AuthenticatedAppNetWorthFlowRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/insurance-gap': {
      id: '/_authenticated/app/insurance-gap'
      path: '/insurance-gap'
      fullPath: '/app/insurance-gap'
      preLoaderRoute: typeof AuthenticatedAppInsuranceGapRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/goals': {
      id: '/_authenticated/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AuthenticatedAppGoalsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/debt-payoff': {
      id: '/_authenticated/app/debt-payoff'
      path: '/debt-payoff'
      fullPath: '/app/debt-payoff'
      preLoaderRoute: typeof AuthenticatedAppDebtPayoffRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cost-of-living': {
      id: '/_authenticated/app/cost-of-living'
      path: '/cost-of-living'
      fullPath: '/app/cost-of-living'
      preLoaderRoute: typeof AuthenticatedAppCostOfLivingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assets': {
      id: '/_authenticated/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AuthenticatedAppAssetsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/advisor/': {
      id: '/_authenticated/app/advisor/'
      path: '/advisor'
      fullPath: '/app/advisor/'
      preLoaderRoute: typeof AuthenticatedAppAdvisorIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/advisor/$threadId': {
      id: '/_authenticated/app/advisor/$threadId'
      path: '/advisor/$threadId'
      fullPath: '/app/advisor/$threadId'
      preLoaderRoute: typeof AuthenticatedAppAdvisorThreadIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAssetsRoute: typeof AuthenticatedAppAssetsRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppCostOfLivingRoute: typeof AuthenticatedAppCostOfLivingRoute
  AuthenticatedAppDebtPayoffRoute: typeof AuthenticatedAppDebtPayoffRoute
  AuthenticatedAppGoalsRoute: typeof AuthenticatedAppGoalsRoute
  AuthenticatedAppInsuranceGapRoute: typeof AuthenticatedAppInsuranceGapRoute
  AuthenticatedAppNetWorthFlowRoute: typeof AuthenticatedAppNetWorthFlowRoute
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppPortfolioPlanRoute: typeof AuthenticatedAppPortfolioPlanRoute
  AuthenticatedAppRadarRoute: typeof AuthenticatedAppRadarRoute
  AuthenticatedAppReportRoute: typeof AuthenticatedAppReportRoute
  AuthenticatedAppResearchRoute: typeof AuthenticatedAppResearchRoute
  AuthenticatedAppRetirementRoute: typeof AuthenticatedAppRetirementRoute
  AuthenticatedAppRoadmapRoute: typeof AuthenticatedAppRoadmapRoute
  AuthenticatedAppScenariosSimulatorRoute: typeof AuthenticatedAppScenariosSimulatorRoute
  AuthenticatedAppSuperOptimizerRoute: typeof AuthenticatedAppSuperOptimizerRoute
  AuthenticatedAppTaxBracketVisualizerRoute: typeof AuthenticatedAppTaxBracketVisualizerRoute
  AuthenticatedAppTaxOptimizerRoute: typeof AuthenticatedAppTaxOptimizerRoute
  AuthenticatedAppToolsRoute: typeof AuthenticatedAppToolsRoute
  AuthenticatedAppTransactionsRoute: typeof AuthenticatedAppTransactionsRoute
  AuthenticatedAppVaultRoute: typeof AuthenticatedAppVaultRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAdvisorThreadIdRoute: typeof AuthenticatedAppAdvisorThreadIdRoute
  AuthenticatedAppAdvisorIndexRoute: typeof AuthenticatedAppAdvisorIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAssetsRoute: AuthenticatedAppAssetsRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppCostOfLivingRoute: AuthenticatedAppCostOfLivingRoute,
  AuthenticatedAppDebtPayoffRoute: AuthenticatedAppDebtPayoffRoute,
  AuthenticatedAppGoalsRoute: AuthenticatedAppGoalsRoute,
  AuthenticatedAppInsuranceGapRoute: AuthenticatedAppInsuranceGapRoute,
  AuthenticatedAppNetWorthFlowRoute: AuthenticatedAppNetWorthFlowRoute,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppPortfolioPlanRoute: AuthenticatedAppPortfolioPlanRoute,
  AuthenticatedAppRadarRoute: AuthenticatedAppRadarRoute,
  AuthenticatedAppReportRoute: AuthenticatedAppReportRoute,
  AuthenticatedAppResearchRoute: AuthenticatedAppResearchRoute,
  AuthenticatedAppRetirementRoute: AuthenticatedAppRetirementRoute,
  AuthenticatedAppRoadmapRoute: AuthenticatedAppRoadmapRoute,
  AuthenticatedAppScenariosSimulatorRoute:
    AuthenticatedAppScenariosSimulatorRoute,
  AuthenticatedAppSuperOptimizerRoute: AuthenticatedAppSuperOptimizerRoute,
  AuthenticatedAppTaxBracketVisualizerRoute:
    AuthenticatedAppTaxBracketVisualizerRoute,
  AuthenticatedAppTaxOptimizerRoute: AuthenticatedAppTaxOptimizerRoute,
  AuthenticatedAppToolsRoute: AuthenticatedAppToolsRoute,
  AuthenticatedAppTransactionsRoute: AuthenticatedAppTransactionsRoute,
  AuthenticatedAppVaultRoute: AuthenticatedAppVaultRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAdvisorThreadIdRoute: AuthenticatedAppAdvisorThreadIdRoute,
  AuthenticatedAppAdvisorIndexRoute: AuthenticatedAppAdvisorIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
