/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppVaultRouteImport } from './routes/_authenticated/app.vault'
import { Route as AuthenticatedAppTransactionsRouteImport } from './routes/_authenticated/app.transactions'
import { Route as AuthenticatedAppToolsRouteImport } from './routes/_authenticated/app.tools'
import { Route as AuthenticatedAppRoadmapRouteImport } from './routes/_authenticated/app.roadmap'
import { Route as AuthenticatedAppRetirementRouteImport } from './routes/_authenticated/app.retirement'
import { Route as AuthenticatedAppResearchRouteImport } from './routes/_authenticated/app.research'
import { Route as AuthenticatedAppReportRouteImport } from './routes/_authenticated/app.report'
import { Route as AuthenticatedAppRadarRouteImport } from './routes/_authenticated/app.radar'
import { Route as AuthenticatedAppPortfolioPlanRouteImport } from './routes/_authenticated/app.portfolio-plan'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated/app.onboarding'
import { Route as AuthenticatedAppGoalsRouteImport } from './routes/_authenticated/app.goals'
import { Route as AuthenticatedAppAssetsRouteImport } from './routes/_authenticated/app.assets'
import { Route as AuthenticatedAppAdvisorIndexRouteImport } from './routes/_authenticated/app.advisor.index'
import { Route as AuthenticatedAppAdvisorThreadIdRouteImport } from './routes/_authenticated/app.advisor.$threadId'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppVaultRoute = AuthenticatedAppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTransactionsRoute =
  AuthenticatedAppTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppToolsRoute = AuthenticatedAppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRoadmapRoute = AuthenticatedAppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRetirementRoute =
  AuthenticatedAppRetirementRouteImport.update({
    id: '/retirement',
    path: '/retirement',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppResearchRoute =
  AuthenticatedAppResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReportRoute = AuthenticatedAppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRadarRoute = AuthenticatedAppRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPortfolioPlanRoute =
  AuthenticatedAppPortfolioPlanRouteImport.update({
    id: '/portfolio-plan',
    path: '/portfolio-plan',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGoalsRoute = AuthenticatedAppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAssetsRoute = AuthenticatedAppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdvisorIndexRoute =
  AuthenticatedAppAdvisorIndexRouteImport.update({
    id: '/advisor/',
    path: '/advisor/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdvisorThreadIdRoute =
  AuthenticatedAppAdvisorThreadIdRouteImport.update({
    id: '/advisor/$threadId',
    path: '/advisor/$threadId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/score': typeof ScoreRoute
  '/waitlist': typeof WaitlistRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/assets': typeof AuthenticatedAppAssetsRoute
  '/app/goals': typeof AuthenticatedAppGoalsRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/portfolio-plan': typeof AuthenticatedAppPortfolioPlanRoute
  '/app/radar': typeof AuthenticatedAppRadarRoute
  '/app/report': typeof AuthenticatedAppReportRoute
  '/app/research': typeof AuthenticatedAppResearchRoute
  '/app/retirement': typeof AuthenticatedAppRetirementRoute
  '/app/roadmap': typeof AuthenticatedAppRoadmapRoute
  '/app/tools': typeof AuthenticatedAppToolsRoute
  '/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/app/vault': typeof AuthenticatedAppVaultRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/advisor/$threadId': typeof AuthenticatedAppAdvisorThreadIdRoute
  '/app/advisor/': typeof AuthenticatedAppAdvisorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/score': typeof ScoreRoute
  '/waitlist': typeof WaitlistRoute
  '/app/assets': typeof AuthenticatedAppAssetsRoute
  '/app/goals': typeof AuthenticatedAppGoalsRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/portfolio-plan': typeof AuthenticatedAppPortfolioPlanRoute
  '/app/radar': typeof AuthenticatedAppRadarRoute
  '/app/report': typeof AuthenticatedAppReportRoute
  '/app/research': typeof AuthenticatedAppResearchRoute
  '/app/retirement': typeof AuthenticatedAppRetirementRoute
  '/app/roadmap': typeof AuthenticatedAppRoadmapRoute
  '/app/tools': typeof AuthenticatedAppToolsRoute
  '/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/app/vault': typeof AuthenticatedAppVaultRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/advisor/$threadId': typeof AuthenticatedAppAdvisorThreadIdRoute
  '/app/advisor': typeof AuthenticatedAppAdvisorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/score': typeof ScoreRoute
  '/waitlist': typeof WaitlistRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/assets': typeof AuthenticatedAppAssetsRoute
  '/_authenticated/app/goals': typeof AuthenticatedAppGoalsRoute
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/portfolio-plan': typeof AuthenticatedAppPortfolioPlanRoute
  '/_authenticated/app/radar': typeof AuthenticatedAppRadarRoute
  '/_authenticated/app/report': typeof AuthenticatedAppReportRoute
  '/_authenticated/app/research': typeof AuthenticatedAppResearchRoute
  '/_authenticated/app/retirement': typeof AuthenticatedAppRetirementRoute
  '/_authenticated/app/roadmap': typeof AuthenticatedAppRoadmapRoute
  '/_authenticated/app/tools': typeof AuthenticatedAppToolsRoute
  '/_authenticated/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/_authenticated/app/vault': typeof AuthenticatedAppVaultRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/advisor/$threadId': typeof AuthenticatedAppAdvisorThreadIdRoute
  '/_authenticated/app/advisor/': typeof AuthenticatedAppAdvisorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/score'
    | '/waitlist'
    | '/app'
    | '/app/assets'
    | '/app/goals'
    | '/app/onboarding'
    | '/app/portfolio-plan'
    | '/app/radar'
    | '/app/report'
    | '/app/research'
    | '/app/retirement'
    | '/app/roadmap'
    | '/app/tools'
    | '/app/transactions'
    | '/app/vault'
    | '/app/'
    | '/app/advisor/$threadId'
    | '/app/advisor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/score'
    | '/waitlist'
    | '/app/assets'
    | '/app/goals'
    | '/app/onboarding'
    | '/app/portfolio-plan'
    | '/app/radar'
    | '/app/report'
    | '/app/research'
    | '/app/retirement'
    | '/app/roadmap'
    | '/app/tools'
    | '/app/transactions'
    | '/app/vault'
    | '/app'
    | '/app/advisor/$threadId'
    | '/app/advisor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/score'
    | '/waitlist'
    | '/_authenticated/app'
    | '/_authenticated/app/assets'
    | '/_authenticated/app/goals'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/portfolio-plan'
    | '/_authenticated/app/radar'
    | '/_authenticated/app/report'
    | '/_authenticated/app/research'
    | '/_authenticated/app/retirement'
    | '/_authenticated/app/roadmap'
    | '/_authenticated/app/tools'
    | '/_authenticated/app/transactions'
    | '/_authenticated/app/vault'
    | '/_authenticated/app/'
    | '/_authenticated/app/advisor/$threadId'
    | '/_authenticated/app/advisor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  ScoreRoute: typeof ScoreRoute
  WaitlistRoute: typeof WaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/vault': {
      id: '/_authenticated/app/vault'
      path: '/vault'
      fullPath: '/app/vault'
      preLoaderRoute: typeof AuthenticatedAppVaultRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/transactions': {
      id: '/_authenticated/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AuthenticatedAppTransactionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tools': {
      id: '/_authenticated/app/tools'
      path: '/tools'
      fullPath: '/app/tools'
      preLoaderRoute: typeof AuthenticatedAppToolsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/roadmap': {
      id: '/_authenticated/app/roadmap'
      path: '/roadmap'
      fullPath: '/app/roadmap'
      preLoaderRoute: typeof AuthenticatedAppRoadmapRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/retirement': {
      id: '/_authenticated/app/retirement'
      path: '/retirement'
      fullPath: '/app/retirement'
      preLoaderRoute: typeof AuthenticatedAppRetirementRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/research': {
      id: '/_authenticated/app/research'
      path: '/research'
      fullPath: '/app/research'
      preLoaderRoute: typeof AuthenticatedAppResearchRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/report': {
      id: '/_authenticated/app/report'
      path: '/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AuthenticatedAppReportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/radar': {
      id: '/_authenticated/app/radar'
      path: '/radar'
      fullPath: '/app/radar'
      preLoaderRoute: typeof AuthenticatedAppRadarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/portfolio-plan': {
      id: '/_authenticated/app/portfolio-plan'
      path: '/portfolio-plan'
      fullPath: '/app/portfolio-plan'
      preLoaderRoute: typeof AuthenticatedAppPortfolioPlanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/goals': {
      id: '/_authenticated/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AuthenticatedAppGoalsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assets': {
      id: '/_authenticated/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AuthenticatedAppAssetsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/advisor/': {
      id: '/_authenticated/app/advisor/'
      path: '/advisor'
      fullPath: '/app/advisor/'
      preLoaderRoute: typeof AuthenticatedAppAdvisorIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/advisor/$threadId': {
      id: '/_authenticated/app/advisor/$threadId'
      path: '/advisor/$threadId'
      fullPath: '/app/advisor/$threadId'
      preLoaderRoute: typeof AuthenticatedAppAdvisorThreadIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAssetsRoute: typeof AuthenticatedAppAssetsRoute
  AuthenticatedAppGoalsRoute: typeof AuthenticatedAppGoalsRoute
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppPortfolioPlanRoute: typeof AuthenticatedAppPortfolioPlanRoute
  AuthenticatedAppRadarRoute: typeof AuthenticatedAppRadarRoute
  AuthenticatedAppReportRoute: typeof AuthenticatedAppReportRoute
  AuthenticatedAppResearchRoute: typeof AuthenticatedAppResearchRoute
  AuthenticatedAppRetirementRoute: typeof AuthenticatedAppRetirementRoute
  AuthenticatedAppRoadmapRoute: typeof AuthenticatedAppRoadmapRoute
  AuthenticatedAppToolsRoute: typeof AuthenticatedAppToolsRoute
  AuthenticatedAppTransactionsRoute: typeof AuthenticatedAppTransactionsRoute
  AuthenticatedAppVaultRoute: typeof AuthenticatedAppVaultRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAdvisorThreadIdRoute: typeof AuthenticatedAppAdvisorThreadIdRoute
  AuthenticatedAppAdvisorIndexRoute: typeof AuthenticatedAppAdvisorIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAssetsRoute: AuthenticatedAppAssetsRoute,
  AuthenticatedAppGoalsRoute: AuthenticatedAppGoalsRoute,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppPortfolioPlanRoute: AuthenticatedAppPortfolioPlanRoute,
  AuthenticatedAppRadarRoute: AuthenticatedAppRadarRoute,
  AuthenticatedAppReportRoute: AuthenticatedAppReportRoute,
  AuthenticatedAppResearchRoute: AuthenticatedAppResearchRoute,
  AuthenticatedAppRetirementRoute: AuthenticatedAppRetirementRoute,
  AuthenticatedAppRoadmapRoute: AuthenticatedAppRoadmapRoute,
  AuthenticatedAppToolsRoute: AuthenticatedAppToolsRoute,
  AuthenticatedAppTransactionsRoute: AuthenticatedAppTransactionsRoute,
  AuthenticatedAppVaultRoute: AuthenticatedAppVaultRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAdvisorThreadIdRoute: AuthenticatedAppAdvisorThreadIdRoute,
  AuthenticatedAppAdvisorIndexRoute: AuthenticatedAppAdvisorIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  ScoreRoute: ScoreRoute,
  WaitlistRoute: WaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
