services:
  - type: web
    runtime: node
    name: app
    buildCommand: npm install && npm run migrate && npm run build:client
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
  - type: worker
    runtime: node
    name: maal-import-worker
    buildCommand: npm install && npm run migrate
    startCommand: npm run worker
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: BASIQ_API_KEY
        sync: false
