function money(value) { const n = Number(value); return Number.isFinite(n) ? Math.max(0, n) : 0; }
function round(value, places = 2) { const p = 10 ** places; return Math.round((value + Number.EPSILON) * p) / p; }
function monthStart(value) { const d = new Date(`${String(value).slice(0, 10)}T00:00:00Z`); return new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), 1)); }
function addMonths(date, months) { const d = monthStart(date.toISOString().slice(0, 10)); d.setUTCMonth(d.getUTCMonth() + months); return d.toISOString().slice(0, 10); }
function monthDifference(from, to) { const a = monthStart(from), b = monthStart(to); return Math.max(0, (b.getUTCFullYear()-a.getUTCFullYear())*12+b.getUTCMonth()-a.getUTCMonth()); }
function goalFeasibility(goal, options = {}) {
  const asOf = options.asOf || new Date().toISOString().slice(0,10), target = money(goal.target_amount ?? goal.target), current = money(goal.current_amount ?? goal.current), remaining = round(Math.max(0,target-current));
  const months = goal.target_date ? monthDifference(asOf, goal.target_date) : null, required = remaining===0 ? 0 : months>0 ? round(remaining/months) : null, contribution = money(options.monthlyContribution ?? goal.monthly_contribution);
  const status = remaining===0 ? 'achieved' : months==null ? 'needs_target_date' : months===0 ? 'overdue' : contribution>=required ? 'on_track' : 'behind';
  return { goal_id:goal.id, name:goal.name, target_amount:target, current_amount:current, remaining_amount:remaining, target_date:goal.target_date||null, months_remaining:months, required_monthly_contribution:required, planned_monthly_contribution:contribution, monthly_shortfall:required==null?null:round(Math.max(0,required-contribution)), status };
}
function emergencyFund({ cash, monthlyEssentialExpenses, targetMonths=6 }) {
  const available=money(cash), expenses=money(monthlyEssentialExpenses), months=Math.max(1,money(targetMonths)||6), target=round(expenses*months);
  return { available_cash:available, monthly_essential_expenses:expenses, coverage_months:expenses?round(available/expenses,1):null, target_months:months, target_amount:target, gap:round(Math.max(0,target-available)), funded_pct:target?round(Math.min(100,available/target*100),1):null, status:!expenses?'needs_expense_data':available>=target?'funded':'building' };
}
function orderedIndexes(debts,strategy,customOrder=[]) { const indexes=debts.map((_,i)=>i); if(strategy==='custom') return indexes.sort((a,b)=>{const ai=customOrder.map(String).indexOf(String(debts[a].id)),bi=customOrder.map(String).indexOf(String(debts[b].id));return(ai<0?1e9:ai)-(bi<0?1e9:bi)}); if(strategy==='snowball') return indexes.sort((a,b)=>money(debts[a].balance)-money(debts[b].balance)); return indexes.sort((a,b)=>money(debts[b].interest_rate)-money(debts[a].interest_rate)); }
function debtPayoff(inputDebts,options={}) {
  const debts=inputDebts.map(d=>({...d,balance:money(d.balance),interest_rate:money(d.interest_rate),min_payment:money(d.min_payment)})).filter(d=>d.balance>0), strategy=['avalanche','snowball','custom'].includes(options.strategy)?options.strategy:'avalanche', order=orderedIndexes(debts,strategy,options.customOrder||[]), balances=debts.map(d=>d.balance), payoffMonth=debts.map(()=>null), schedule=[];
  const budget=debts.reduce((s,d)=>s+d.min_payment,0)+money(options.extraMonthly); let interestTotal=0,month=0;
  while(balances.some(b=>b>0.005)&&month<1200){month++;let available=budget,monthInterest=0;for(let i=0;i<debts.length;i++){if(!balances[i])continue;const interest=balances[i]*debts[i].interest_rate/1200;balances[i]+=interest;interestTotal+=interest;monthInterest+=interest;const pay=Math.min(balances[i],debts[i].min_payment,available);balances[i]-=pay;available-=pay;}for(const i of order){if(available<=0||balances[i]<=0)continue;const pay=Math.min(balances[i],available);balances[i]-=pay;available-=pay;}balances.forEach((b,i)=>{if(b<=0.005&&payoffMonth[i]==null){balances[i]=0;payoffMonth[i]=month;}});schedule.push({month,date:addMonths(new Date(`${options.asOf||new Date().toISOString().slice(0,10)}T00:00:00Z`),month),interest:round(monthInterest),closing_balance:round(balances.reduce((a,b)=>a+b,0))});if(budget<=0)break;}
  const completed=balances.every(b=>b===0); return {strategy,monthly_budget:round(budget),extra_monthly:money(options.extraMonthly),starting_balance:round(debts.reduce((s,d)=>s+d.balance,0)),total_interest:round(interestTotal),months_to_debt_free:completed?month:null,debt_free_date:completed?addMonths(new Date(`${options.asOf||new Date().toISOString().slice(0,10)}T00:00:00Z`),month):null,payoff_order:order.map(i=>({id:debts[i].id,label:debts[i].label,payoff_month:payoffMonth[i]})),schedule,feasible:completed};
}
function buildPlanningSummary(input){const contributions=input.goalContributions||{},goals=(input.goals||[]).map(g=>goalFeasibility(g,{asOf:input.asOf,monthlyContribution:contributions[g.id]??g.monthly_contribution})),emergency=emergencyFund({cash:input.cash,monthlyEssentialExpenses:input.monthlyEssentialExpenses,targetMonths:input.emergencyTargetMonths}),strategies=['avalanche','snowball','custom'].map(strategy=>debtPayoff(input.debts||[],{strategy,customOrder:input.customDebtOrder,extraMonthly:input.extraDebtPayment,asOf:input.asOf})),best=strategies.filter(p=>p.feasible&&p.strategy!=='custom').sort((a,b)=>a.total_interest-b.total_interest)[0];return{as_of:input.asOf||new Date().toISOString().slice(0,10),goals,emergency_fund:emergency,debt_plans:strategies,outcomes:{goals_on_track:goals.filter(g=>['on_track','achieved'].includes(g.status)).length,goals_total:goals.length,emergency_fund_gap:emergency.gap,debt_reduction_target:best?.starting_balance||0,projected_debt_free_date:best?.debt_free_date||null,recommended_debt_strategy:best?.strategy||null}};}
module.exports={goalFeasibility,emergencyFund,debtPayoff,buildPlanningSummary,monthDifference};
