const pool = require('./pool');
async function createHousehold(userId,name){const c=await pool.connect();try{await c.query('BEGIN');const h=await c.query('INSERT INTO households(name,created_by) VALUES($1,$2) RETURNING *',[name,userId]);await c.query("INSERT INTO household_members(household_id,user_id,role) VALUES($1,$2,'owner')",[h.rows[0].id,userId]);await c.query('COMMIT');return h.rows[0]}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
async function listHouseholds(userId){return(await pool.query('SELECT h.*,hm.role,hm.ownership FROM households h JOIN household_members hm ON hm.household_id=h.id WHERE hm.user_id=$1 ORDER BY h.created_at',[userId])).rows}
async function addMember(householdId,actorId,userId,ownership=100){return(await pool.query("INSERT INTO household_members(household_id,user_id,role,ownership) SELECT $1,$3,'member',$4 WHERE EXISTS (SELECT 1 FROM household_members WHERE household_id=$1 AND user_id=$2 AND role='owner') ON CONFLICT (household_id,user_id) DO UPDATE SET ownership=EXCLUDED.ownership RETURNING *",[householdId,actorId,userId,ownership])).rows[0]||null}
async function listGrants(userId){return(await pool.query('SELECT * FROM access_grants WHERE owner_user_id=$1 ORDER BY created_at DESC',[userId])).rows}
async function createGrant(userId,g){return(await pool.query('INSERT INTO access_grants(owner_user_id,grantee_email,role,scopes,expires_at) VALUES($1,$2,$3,$4,$5) RETURNING *',[userId,g.email,g.role,g.scopes||['overview'],g.expiresAt||null])).rows[0]}
async function revokeGrant(userId,id){return(await pool.query("UPDATE access_grants SET status='revoked',revoked_at=NOW() WHERE id=$1 AND owner_user_id=$2 RETURNING *",[id,userId])).rows[0]||null}
async function listDocuments(userId,taxYear){return(await pool.query('SELECT * FROM supporting_documents WHERE user_id=$1 AND ($2::int IS NULL OR tax_year=$2) ORDER BY created_at DESC',[userId,taxYear||null])).rows}
module.exports={createHousehold,listHouseholds,addMember,listGrants,createGrant,revokeGrant,listDocuments};
