const pool = require('./pool');
const { hashToken, createToken, normaliseScopes } = require('../lib/extensibility');
async function createNotification(userId,type,title,body,data={}) { return (await pool.query('INSERT INTO notifications(user_id,type,title,body,data) VALUES($1,$2,$3,$4,$5) RETURNING *',[userId,type,title,body,JSON.stringify(data)])).rows[0]; }
async function listNotifications(userId,limit=50) { return (await pool.query('SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2',[userId,Math.min(Number(limit)||50,100)])).rows; }
async function markNotificationsRead(userId,ids=[]) { if(ids.length) await pool.query('UPDATE notifications SET read_at=NOW() WHERE user_id=$1 AND id=ANY($2::bigint[])',[userId,ids]); }
async function recordActivity(e) { return (await pool.query('INSERT INTO activity_ledger(actor_user_id,subject_user_id,action,resource_type,resource_id,metadata,ip_address) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[e.actorUserId||null,e.subjectUserId||e.actorUserId||null,e.action,e.resourceType||null,e.resourceId==null?null:String(e.resourceId),JSON.stringify(e.metadata||{}),e.ip||null])).rows[0]; }
async function createApiToken(userId,name,scopes,expiresAt) { const t=createToken(); const row=(await pool.query('INSERT INTO api_tokens(user_id,name,token_hash,scopes,expires_at) VALUES($1,$2,$3,$4,$5) RETURNING id,name,scopes,expires_at,created_at',[userId,name,t.hash,normaliseScopes(scopes),expiresAt||null])).rows[0]; return {...row,token:t.token}; }
async function authenticateToken(token) { const r=await pool.query('SELECT * FROM api_tokens WHERE token_hash=$1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>NOW())',[hashToken(token)]); if(!r.rows[0]) return null; await pool.query('UPDATE api_tokens SET last_used_at=NOW() WHERE id=$1',[r.rows[0].id]); return r.rows[0]; }
module.exports={createNotification,listNotifications,markNotificationsRead,recordActivity,createApiToken,authenticateToken};
